services:
  app:
    build: .
    ports:
      - "1337:1337"
    environment:
      - PORT=1337
      - GOOGLE_APPLICATION_CREDENTIALS=secrets/google-api-key.json
    volumes:
      - ./secrets:/app/secrets
    restart: unless-stopped
