name: GitHub Actions demo

on:
  push:
    branches: [master]

jobs:
  Test-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello testing"
      - name: SSH into droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/johns-predictions
            git pull origin master
            docker compose down
            docker compose up -d --build
